In [1]:
from pathlib import Path

import numpy as np
import pandas as pd

pd.set_option("display.max_columns", None)
pd.set_option("display.float_format", lambda x: f"{x:,.2f}")

In [2]:
DATA_DIR = Path("../data")

TRAIN_PATH = DATA_DIR / "train_test.csv"
VALIDATION_PATH = DATA_DIR / "validation.csv"

train = pd.read_csv(TRAIN_PATH)
validation = pd.read_csv(VALIDATION_PATH)

print("Training shape:", train.shape)
print("Validation shape:", validation.shape)

Training shape: (48000, 14)
Validation shape: (12000, 13)

In [3]:
print("TRAINING")
print("Missing:", train["weight"].isnull().sum())
print("Negative:", (train["weight"] < 0).sum())

print()

print("VALIDATION")
print("Missing:", validation["weight"].isnull().sum())
print("Negative:", (validation["weight"] < 0).sum())

TRAINING
Missing: 300
Negative: 292

VALIDATION
Missing: 165
Negative: 145

In [4]:
train["weight_missing"] = train["weight"].isnull().astype(int)

validation["weight_missing"] = validation["weight"].isnull().astype(int)

In [5]:
print(
    train["weight_missing"].value_counts()
)

weight_missing
0    47700
1      300
Name: count, dtype: int64

In [6]:
train["weight"] = train["weight"].abs()

validation["weight"] = validation["weight"].abs()

In [7]:
print(
    "Training negative weights:",
    (train["weight"] < 0).sum()
)

print(
    "Validation negative weights:",
    (validation["weight"] < 0).sum()
)

Training negative weights: 0
Validation negative weights: 0

In [8]:
weight_median = train["weight"].median()

print("Training median weight:", weight_median)

Training median weight: 31496.0

In [9]:
train["weight"] = train["weight"].fillna(weight_median)

validation["weight"] = validation["weight"].fillna(weight_median)

In [10]:
validation["weight"].fillna(weight_median)

0       19,958.00
1       34,114.00
2       33,435.00
3       25,392.00
4       31,496.00
           ...
11995   38,638.00
11996   27,685.00
11997   35,522.00
11998   31,755.00
11999   39,571.00
Name: weight, Length: 12000, dtype: float64

In [11]:
validation["weight"].fillna(
    validation["weight"].median()
)

0       19,958.00
1       34,114.00
2       33,435.00
3       25,392.00
4       31,496.00
           ...
11995   38,638.00
11996   27,685.00
11997   35,522.00
11998   31,755.00
11999   39,571.00
Name: weight, Length: 12000, dtype: float64

In [12]:
print("Training missing:", train["weight"].isnull().sum())
print("Validation missing:", validation["weight"].isnull().sum())

print("Training negative:", (train["weight"] < 0).sum())
print("Validation negative:", (validation["weight"] < 0).sum())

Training missing: 0
Validation missing: 0
Training negative: 0
Validation negative: 0

In [13]:
train["market_index_missing"] = (
    train["market_index"].isnull().astype(int)
)

validation["market_index_missing"] = (
    validation["market_index"].isnull().astype(int)
)

In [14]:
print(
    train["market_index_missing"].value_counts()
)

market_index_missing
0    47626
1      374
Name: count, dtype: int64

In [15]:
market_median = train["market_index"].median()

print("Training market median:", market_median)

Training market median: 1.0558

In [16]:
train["market_index"] = (
    train["market_index"].fillna(market_median)
)

validation["market_index"] = (
    validation["market_index"].fillna(market_median)
)

In [17]:
print(
    "Training missing:",
    train["market_index"].isnull().sum()
)

print(
    "Validation missing:",
    validation["market_index"].isnull().sum()
)

Training missing: 0
Validation missing: 0

In [18]:
print(
    "Training missing quote signal:",
    train["quote_signal"].isnull().sum()
)

print(
    "Validation missing quote signal:",
    validation["quote_signal"].isnull().sum()
)

Training missing quote signal: 0
Validation missing quote signal: 0

In [19]:
train["date"] = pd.to_datetime(train["date"])

validation["date"] = pd.to_datetime(validation["date"])

In [20]:
print(train["date"].dtype)
print(validation["date"].dtype)

datetime64[ns]
datetime64[ns]

In [21]:
train["day_of_week"] = train["date"].dt.dayofweek

validation["day_of_week"] = validation["date"].dt.dayofweek

In [22]:
train[
    ["date", "day_of_week"]
].head()

        date  day_of_week
0 2025-01-01            2
1 2025-01-01            2
2 2025-01-01            2
3 2025-01-01            2
4 2025-01-01            2

In [23]:
train["month"] = train["date"].dt.month

validation["month"] = validation["date"].dt.month

In [24]:
train["day_of_month"] = train["date"].dt.day

validation["day_of_month"] = validation["date"].dt.day

In [25]:
train["week_of_year"] = (
    train["date"].dt.isocalendar().week.astype(int)
)

validation["week_of_year"] = (
    validation["date"].dt.isocalendar().week.astype(int)
)

In [26]:
train["is_weekend"] = (
    train["day_of_week"] >= 5
).astype(int)

validation["is_weekend"] = (
    validation["day_of_week"] >= 5
).astype(int)

In [27]:
train[
    [
        "date",
        "month",
        "week_of_year",
        "day_of_month",
        "day_of_week",
        "is_weekend"
    ]
].head(10)

        date  month  week_of_year  day_of_month  day_of_week  is_weekend
0 2025-01-01      1             1             1            2           0
1 2025-01-01      1             1             1            2           0
2 2025-01-01      1             1             1            2           0
3 2025-01-01      1             1             1            2           0
4 2025-01-01      1             1             1            2           0
5 2025-01-01      1             1             1            2           0
6 2025-01-01      1             1             1            2           0
7 2025-01-01      1             1             1            2           0
8 2025-01-01      1             1             1            2           0
9 2025-01-01      1             1             1            2           0

In [28]:
train["log_distance"] = np.log1p(train["distance"])

validation["log_distance"] = np.log1p(
    validation["distance"]
)

In [29]:
train[
    [
        "distance",
        "log_distance"
    ]
].head(10)

   distance  log_distance
0    274.30          5.62
1    280.50          5.64
2    967.80          6.88
3    965.40          6.87
4    541.90          6.30
5  1,396.40          7.24
6  1,502.60          7.32
7  1,976.90          7.59
8  2,027.70          7.62
9    717.10          6.58

In [30]:
train["log_weight"] = np.log1p(train["weight"])

validation["log_weight"] = np.log1p(
    validation["weight"]
)

In [31]:
train[
    [
        "weight",
        "log_weight",
        "weight_missing"
    ]
].head()

     weight  log_weight  weight_missing
0 30,658.00       10.33               0
1 17,555.00        9.77               0
2 31,721.00       10.36               0
3 32,333.00       10.38               0
4 35,183.00       10.47               0

In [32]:
train["lane"] = (
    train["pickup"]
    + " -> "
    + train["delivery"]
)

validation["lane"] = (
    validation["pickup"]
    + " -> "
    + validation["delivery"]
)

In [33]:
train[
    [
        "pickup",
        "delivery",
        "lane"
    ]
].head()

         pickup      delivery                       lane
0      Richmond     Baltimore      Richmond -> Baltimore
1      Richmond  Philadelphia   Richmond -> Philadelphia
2  Philadelphia     Green Bay  Philadelphia -> Green Bay
3      Hartford       Atlanta        Hartford -> Atlanta
4        Dallas     Nashville        Dallas -> Nashville

In [34]:
train["equipment"] = train["equipment"].astype("category")

validation["equipment"] = validation["equipment"].astype("category")

In [35]:
print(train["equipment"].dtype)

print(
    train["equipment"].cat.categories
)

category
Index(['Dry Van', 'Flatbed', 'Reefer'], dtype='object')

In [36]:
pickup_categories = sorted(
    set(train["pickup"]) | set(validation["pickup"])
)

delivery_categories = sorted(
    set(train["delivery"]) | set(validation["delivery"])
)


train["pickup"] = pd.Categorical(
    train["pickup"],
    categories=pickup_categories
)

validation["pickup"] = pd.Categorical(
    validation["pickup"],
    categories=pickup_categories
)



train["delivery"] = pd.Categorical(
    train["delivery"],
    categories=delivery_categories
)

validation["delivery"] = pd.Categorical(
    validation["delivery"],
    categories=delivery_categories
)

In [37]:
train_lanes = set(train["lane"])


train["new_lane"] = 0

validation["new_lane"] = (
    ~validation["lane"].isin(train_lanes)
).astype(int)


validation["lane"] = validation["lane"].where(
    validation["lane"].isin(train_lanes),
    "UNKNOWN_LANE"
)


lane_categories = sorted(train_lanes) + ["UNKNOWN_LANE"]

train["lane"] = pd.Categorical(
    train["lane"],
    categories=lane_categories
)

validation["lane"] = pd.Categorical(
    validation["lane"],
    categories=lane_categories
)

In [38]:
train["log_posted_rate"] = np.log(
    train["posted_rate"]
)

In [39]:
train[
    [
        "posted_rate",
        "log_posted_rate"
    ]
].head()

   posted_rate  log_posted_rate
0       645.41             6.47
1       679.97             6.52
2     1,802.54             7.50
3     1,827.28             7.51
4     1,380.28             7.23

In [40]:
'''posted_rate
    │
    │ log()
    ↓
log_posted_rate
    │
    │ MODEL
    ↓
prediction
    │
    │ exp()
    ↓
predicted_rate'''

'posted_rate\n    │\n    │ log()\n    ↓\nlog_posted_rate\n    │\n    │ MODEL\n    ↓\nprediction\n    │\n    │ exp()\n    ↓\npredicted_rate'

In [41]:
FEATURES = [
    # Freight
    "distance",
    "log_distance",
    "weight",
    "log_weight",
    "weight_missing",
    "equipment",

    # Geography
    "pickup",
    "delivery",
    "pickup_lat",
    "pickup_lon",
    "delivery_lat",
    "delivery_lon",
    "lane",

    # Market
    "market_index",
    "market_index_missing",
    "quote_signal",

    # Time
    "month",
    "week_of_year",
    "day_of_month",
    "day_of_week",
    "is_weekend"
]

TARGET = "log_posted_rate"

In [42]:
X = train[FEATURES]

y = train[TARGET]

X_validation = validation[FEATURES]

In [43]:
print("X shape:", X.shape)
print("y shape:", y.shape)
print("Validation X shape:", X_validation.shape)

X shape: (48000, 21)
y shape: (48000,)
Validation X shape: (12000, 21)

In [44]:
print("Training missing values:")

print(
    X.isnull().sum()
)

Training missing values:
distance                0
log_distance            0
weight                  0
log_weight              0
weight_missing          0
equipment               0
pickup                  0
delivery                0
pickup_lat              0
pickup_lon              0
delivery_lat            0
delivery_lon            0
lane                    0
market_index            0
market_index_missing    0
quote_signal            0
month                   0
week_of_year            0
day_of_month            0
day_of_week             0
is_weekend              0
dtype: int64

In [45]:
print("Validation missing values:")

print(
    X_validation.isnull().sum()
)

Validation missing values:
distance                0
log_distance            0
weight                  0
log_weight              0
weight_missing          0
equipment               0
pickup                  0
delivery                0
pickup_lat              0
pickup_lon              0
delivery_lat            0
delivery_lon            0
lane                    0
market_index            0
market_index_missing    0
quote_signal            0
month                   0
week_of_year            0
day_of_month            0
day_of_week             0
is_weekend              0
dtype: int64

In [46]:
print("FINAL FEATURE ENGINEERING CHECK")
print("=" * 50)

print("Training rows:", len(X))
print("Validation rows:", len(X_validation))

print()

print("Number of features:", len(FEATURES))

print()

print("Target missing:", y.isnull().sum())

print()

print(
    "Training infinite values:",
    np.isinf(
        X.select_dtypes(include=np.number)
    ).sum().sum()
)

print(
    "Validation infinite values:",
    np.isinf(
        X_validation.select_dtypes(include=np.number)
    ).sum().sum()
)

FINAL FEATURE ENGINEERING CHECK
==================================================
Training rows: 48000
Validation rows: 12000

Number of features: 21

Target missing: 0

Training infinite values: 0
Validation infinite values: 0

In [47]:
print("Training missing features:")
print(X.isnull().sum()[X.isnull().sum() > 0])

print("\nValidation missing features:")
print(X_validation.isnull().sum()[X_validation.isnull().sum() > 0])

Training missing features:
Series([], dtype: int64)

Validation missing features:
Series([], dtype: int64)

In [48]:
PROCESSED_DIR = DATA_DIR / "processed"

PROCESSED_DIR.mkdir(exist_ok=True)


train.to_csv(
    PROCESSED_DIR / "train_processed.csv",
    index=False
)

validation.to_csv(
    PROCESSED_DIR / "validation_processed.csv",
    index=False
)

print("Processed data saved successfully.")

Processed data saved successfully.

In [49]:
print(
    "Train saved:",
    (PROCESSED_DIR / "train_processed.csv").exists()
)

print(
    "Validation saved:",
    (PROCESSED_DIR / "validation_processed.csv").exists()
)

Train saved: True
Validation saved: True